const SPOTIFY_BASE_URL = 'https://api.spotify.com'
const SPOTIFY_ACCOUNT_BASE_URL = 'https://accounts.spotify.com'

export const SPOTIFY_REQUEST_AUTHORIZATION_ENDPOINT = new URL('/authorize', SPOTIFY_ACCOUNT_BASE_URL)
export const SPOTIFY_REQUEST_TOKEN_ENDPOINT = new URL('/api/token', SPOTIFY_ACCOUNT_BASE_URL)

export const SPOTIFY_CURRENT_PROFILE_ENDPOINT = new URL('/v1/me', SPOTIFY_BASE_URL)
export const SPOTIFY_SEARCH_ENDPOINT = new URL('/v1/search', SPOTIFY_BASE_URL)
export const SPOTIFY_SAVE_ALBUMS_ENDPOINT = new URL('/v1/me/albums', SPOTIFY_BASE_URL)

export const SPOTIFY_OAUTH_CONFIRM_SUCCESS = 'SPOTIFY_OAUTH_CONFIRM_SUCCESS'

export const SPOTIFY_FETCH_USER_INFO = 'SPOTIFY_FETCH_USER_INFO'
export const SPOTIFY_FETCH_USER_INFO_SUCCESS = 'SPOTIFY_FETCH_USER_INFO_SUCCESS'
export const SPOTIFY_FETCH_USER_INFO_FAIL = 'SPOTIFY_FETCH_USER_INFO_FAIL'

export const SPOTIFY_SEARCH_ALBUM = 'SPOTIFY_SEARCH_ALBUM'
export const SPOTIFY_SEARCH_ALBUM_SUCCESS = 'SPOTIFY_SEARCH_ALBUM_SUCCESS'
export const SPOTIFY_SEARCH_ALBUM_FAIL = 'SPOTIFY_SEARCH_ALBUM_FAIL'
